//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitchellClaimDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LossInfoType
    {
        public string ClaimNumber { get; set; }
        public string LossCause { get; set; }
        public Nullable<System.DateTime> ReportedDate { get; set; }
        public string LossDescription { get; set; }
    
        public virtual MitchellClaimType MitchellClaimType { get; set; }
    }
}
