//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitchellClaimDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MitchellClaimType
    {
        public string ClaimNumber { get; set; }
        public string ClaimantFirstName { get; set; }
        public string ClaimantLastName { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LossDate { get; set; }
        public Nullable<long> AssignedAdjusterID { get; set; }
    
        public virtual LossInfoType LossInfoType { get; set; }
    }
}
